/*
 * Copyright (c) 2022 Huawei Technologies Co.,Ltd.
 *
 * WR is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *
 *          http://license.coscl.org.cn/MulanPSL2
 *
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 * -------------------------------------------------------------------------
 *
 * wr_session.h
 *
 *
 * IDENTIFICATION
 *    src/common/wr_session.h
 *
 * -------------------------------------------------------------------------
 */

#ifndef __WR_SESSION_H__
#define __WR_SESSION_H__

#include "cm_defs.h"
#include "cm_thread_pool.h"
#include "cm_date.h"
#include "cs_packet.h"
#include "cs_pipe.h"
#include "wr_defs.h"
#include "wr_au.h"
#include "wr_log.h"
#include "wr_protocol.h"
#include "wr_latch.h"
#include "wr_stats.h"
#include "wr_shm.h"

#ifdef __cplusplus
extern "C" {
#endif

#define WR_INVALID_SESSIONID CM_INVALID_ID32
#define WR_MAX_LATCH_STACK_BOTTON 0
#define WR_MAX_LATCH_STACK_DEPTH 8
#define WR_LOCK_CLEAN_SLEEP_TIME 500
#define WR_SESSION_PAUSED_WAIT 50

#define WR_META_SYN_BG_TASK_NUM_MAX 4
#define WR_RECYLE_META_TASK_NUM_MAX 4

#define WR_SERVER_SESS_TIMEOUT 100

#define MAX_FILE_HASH_COUNT 100000
typedef enum st_wr_background_task_type {
    WR_RECOVERY_BACKGROUND_TASK = 0,
    WR_DELAY_CLEAN_BACKGROUND_TASK = 1,
    WR_HASHMAP_DYNAMIC_EXTEND_TASK = 2,
    WR_ALARM_CHECK_TASK = 3,
    WR_META_SYN_BG_TASK_BASE = 4,
    WR_META_SYN_BG_TASK_END = WR_META_SYN_BG_TASK_BASE + WR_META_SYN_BG_TASK_NUM_MAX,
    WR_RECYCLE_META_TASK_BASE = WR_META_SYN_BG_TASK_END,
    WR_RECYCLE_META_TASK_END = WR_RECYCLE_META_TASK_BASE + WR_RECYLE_META_TASK_NUM_MAX,
    WR_BACKGROUND_TASK_NUM = WR_RECYCLE_META_TASK_END,
} wr_background_task_type_e;

typedef struct st_wr_bg_task_info {
    uint32_t task_num_max;
    uint32_t my_task_id;
    uint32_t vg_id_beg;
    uint32_t vg_id_end;
    void *task_args;
} wr_bg_task_info_t;

typedef struct wr_cli_info {
    uint64 cli_pid;
    int64 start_time;
    char process_name[WR_FILE_NAME_BUFFER_SIZE + 1];
    uint32_t thread_id;
    uint64 connect_time;
} wr_cli_info_t;

typedef enum st_wr_latch_offset_type {
    WR_LATCH_OFFSET_INVALID = 0,
    WR_LATCH_OFFSET_UNIQ_ID,
    WR_LATCH_OFFSET_SHMOFFSET,
} wr_latch_offset_type_e;

typedef struct st_wr_latch_offset {
    wr_latch_offset_type_e type;
    union {
        uint32_t unique_id;
        uint64 shm_offset;
    } offset;
} wr_latch_offset_t;

typedef struct st_wr_latch_stack {
    wr_latch_offset_t latch_offset_stack[WR_MAX_LATCH_STACK_DEPTH];
    uint32_t stack_top;
    uint32_t stack_top_bak;
    wr_latch_shared_op_e op;
} wr_latch_stack_t;

typedef enum en_protocol_type {
    PROTO_TYPE_UNKNOWN = 0,
    PROTO_TYPE_GS = 1,
} protocol_type_t;

typedef enum en_wr_session_status {
    WR_SESSION_STATUS_IDLE = 0,
    WR_SESSION_STATUS_RUNNING,
    WR_SESSION_STATUS_PAUSING,
    WR_SESSION_STATUS_PAUSED,
} wr_session_status_t;

typedef struct st_wr_session {
    spinlock_t lock;  // for control current rw of the same session in server
    uint32_t id;
    bool32 is_closed;
    bool32 is_used;
    bool32 connected;
    bool32 reactor_added;
    cs_pipe_t pipe;
    wr_packet_t recv_pack;
    wr_packet_t send_pack;
    text_t send_info;  // send extra info, please use recv_pack.init_buf, len = 0 if no info ack
    ftid_t curr_dir;
    protocol_type_t proto_type;  // gauss or mysql (not realized)
    wr_cli_info_t cli_info;
    wr_latch_stack_t latch_stack;
    volatile uint64 curr_lsn;  // latest lsn generated by current session
    wr_audit_info_t audit_info;
    wr_session_status_t status;
    void *reactor;
    void *workthread_ctx;
    wr_stat_item_t wr_session_stat[WR_EVT_COUNT];
    uint32_t client_version; /* client version */
    uint32_t proto_version;  /* client and server negotiated version */
    uint32_t objectid;
    wr_stat_ctx_t stat_ctx;
    bool8 is_direct;
    bool8 put_log;
    bool8 is_holding_hotpatch_latch;
    spinlock_t shm_lock;  // for control current rw of the same session in shm
    session_hash_mgr_t hash_mgr;
} wr_session_t;

static inline char *wr_init_sendinfo_buf(char *input)
{
    return (input + sizeof(wr_packet_head_t) + sizeof(int32_t));
}

static inline void wr_session_end_stat(wr_session_t *session, timeval_t *begin_tv, wr_wait_event_e event)
{
    if (session != NULL) {
        wr_end_stat_base(&session->wr_session_stat[event], begin_tv);
    }
}

typedef struct st_wr_session_ctrl {
    spinlock_t lock;
    bool32 is_inited;
    uint32_t used_count;
    uint32_t total;
    uint32_t alloc_sessions;
    wr_session_t **sessions;
} wr_session_ctrl_t;

extern wr_session_ctrl_t g_wr_session_ctrl;
status_t wr_init_session_pool(uint32_t max_session_num);
wr_session_ctrl_t *wr_get_session_ctrl(void);
status_t wr_create_session(const cs_pipe_t *pipe, wr_session_t **session);
void wr_destroy_session(wr_session_t *session);
void wr_destroy_session_inner(wr_session_t *session);
wr_session_t *wr_get_session(uint32_t sid);

// only used by api-client or by clean
bool32 wr_unlock_shm_meta_s_with_stack(wr_session_t *session, wr_shared_latch_t *shared_latch, bool32 is_try_lock);
void wr_clean_session_latch(wr_session_t *session, bool32 is_daemon);
uint32_t wr_get_uwression_startid(void);
uint32_t wr_get_recover_task_idx(void);
uint32_t wr_get_max_total_session_cnt(void);
uint32_t wr_get_delay_clean_task_idx(void);
uint32_t wr_get_alarm_check_task_idx(void);
typedef uint32_t (*wr_get_bg_task_idx_func_t)(uint32_t idx);
void wr_server_session_lock(wr_session_t *session);
void wr_server_session_unlock(wr_session_t *session);
wr_session_t *wr_get_reserv_session(uint32_t idx);
status_t init_session_hash_mgr(wr_session_t *session);
status_t update_file_hash(wr_session_t *session, uint32_t file_handle, const uint8_t *new_hash);
status_t get_file_hash(wr_session_t *session, uint32_t file_handle, uint8_t *curr_hash, uint8_t *prev_hash);
status_t generate_random_sha256(unsigned char *hash);

#ifdef __cplusplus
}
#endif

#endif
